[colors.primary]
background = "#111318"
foreground = "#e2e2e9"

[colors.cursor]
text = "#111318"
cursor = "#adc6ff"

[colors.selection]
text = "#102f60"
background = "#adc6ff"

[colors.normal]
black   = "#8e9099"
red     = "#ffb4ab"
green   = "#debcdf"
yellow  = "#bfc6dc"
blue    = "#adc6ff"
magenta = "#bfc6dc"
cyan    = "#debcdf"
white   = "#e2e2e9"

[colors.bright]
black   = "#44474f"
red     = "#ffb4ab"
green   = "#debcdf"
yellow  = "#bfc6dc"
blue    = "#adc6ff"
magenta = "#bfc6dc"
cyan    = "#debcdf"
white   = "#e2e2e9"
