[colors.primary]
background = "#131318"
foreground = "#e5e1e9"

[colors.cursor]
text = "#131318"
cursor = "#c4c0ff"

[colors.selection]
text = "#2c2960"
background = "#c4c0ff"

[colors.normal]
black   = "#928f99"
red     = "#ffb4ab"
green   = "#eab9d1"
yellow  = "#c7c4dc"
blue    = "#c4c0ff"
magenta = "#c7c4dc"
cyan    = "#eab9d1"
white   = "#e5e1e9"

[colors.bright]
black   = "#47464f"
red     = "#ffb4ab"
green   = "#eab9d1"
yellow  = "#c7c4dc"
blue    = "#c4c0ff"
magenta = "#c7c4dc"
cyan    = "#eab9d1"
white   = "#e5e1e9"
