# =========================
# Matugen Dynamic Theme
# =========================

set -g status-position bottom
set -g status-justify centre
set -g status-interval 1

# Status Bar
set -g status-style "bg=#111318,fg=#e2e2e9"

# Left
set -g status-left-length 100
set -g status-left "#[fg=#adc6ff,bold]  #S "

# Right
set -g status-right-length 100
set -g status-right "#[fg=#bfc6dc] %d %b  %H:%M "

# Window Tabs
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "

setw -g window-status-style "fg=#8e9099,bg=#111318"

setw -g window-status-current-style "fg=#102f60,bg=#adc6ff,bold"

# Pane Borders
set -g pane-border-style "fg=#8e9099"
set -g pane-active-border-style "fg=#adc6ff"

# Copy Mode
setw -g mode-style "fg=#111318,bg=#adc6ff"

# Messages
set -g message-style "fg=#e2e2e9,bg=#1e1f25"

# Clock
set -g clock-mode-colour "#adc6ff"

# Popup
set -g popup-style "bg=#111318,fg=#e2e2e9"
set -g popup-border-style "fg=#adc6ff"

# Menus
set -g menu-style "bg=#111318,fg=#e2e2e9"
set -g menu-selected-style "bg=#adc6ff,fg=#102f60"
