# =========================
# Matugen Dynamic Theme
# =========================

set -g status-position bottom
set -g status-justify centre
set -g status-interval 1

# Status Bar
set -g status-style "bg=#131318,fg=#e5e1e9"

# Left
set -g status-left-length 100
set -g status-left "#[fg=#c4c0ff,bold]  #S "

# Right
set -g status-right-length 100
set -g status-right "#[fg=#c7c4dc] %d %b  %H:%M "

# Window Tabs
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "

setw -g window-status-style "fg=#928f99,bg=#131318"

setw -g window-status-current-style "fg=#2c2960,bg=#c4c0ff,bold"

# Pane Borders
set -g pane-border-style "fg=#928f99"
set -g pane-active-border-style "fg=#c4c0ff"

# Copy Mode
setw -g mode-style "fg=#131318,bg=#c4c0ff"

# Messages
set -g message-style "fg=#e5e1e9,bg=#201f25"

# Clock
set -g clock-mode-colour "#c4c0ff"

# Popup
set -g popup-style "bg=#131318,fg=#e5e1e9"
set -g popup-border-style "fg=#c4c0ff"

# Menus
set -g menu-style "bg=#131318,fg=#e5e1e9"
set -g menu-selected-style "bg=#c4c0ff,fg=#2c2960"
