# =========================
# Matugen Dynamic Theme
# =========================

set -g status-position bottom
set -g status-justify centre
set -g status-interval 1

# Status Bar
set -g status-style "bg=#0e1513,fg=#dee4e0"

# Left
set -g status-left-length 100
set -g status-left "#[fg=#85d6bf,bold]  #S "

# Right
set -g status-right-length 100
set -g status-right "#[fg=#b2ccc3] %d %b  %H:%M "

# Window Tabs
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "

setw -g window-status-style "fg=#89938f,bg=#0e1513"

setw -g window-status-current-style "fg=#00382d,bg=#85d6bf,bold"

# Pane Borders
set -g pane-border-style "fg=#89938f"
set -g pane-active-border-style "fg=#85d6bf"

# Copy Mode
setw -g mode-style "fg=#0e1513,bg=#85d6bf"

# Messages
set -g message-style "fg=#dee4e0,bg=#1b211f"

# Clock
set -g clock-mode-colour "#85d6bf"

# Popup
set -g popup-style "bg=#0e1513,fg=#dee4e0"
set -g popup-border-style "fg=#85d6bf"

# Menus
set -g menu-style "bg=#0e1513,fg=#dee4e0"
set -g menu-selected-style "bg=#85d6bf,fg=#00382d"
